<?php

return array (
  'login_page_status' => '1',
  'login_page_title' => 'Login',
  'login_page_description' => '',
  'login_page_image' => 'themes/beauty/assets/images/common-banner.png',
  'login_status' => '1',
  'login_title' => 'Sign In',
  'login_description' => 'Welcome back! Sign in to your account to continue.',
  'login_email' => 'Email Address',
  'login_password' => 'Password',
  'login_remember' => 'Remember me',
  'login_button' => 'Sign In',
  'login_forgot_status' => '1',
  'login_forgot_link' => 'Forgot password?',
  'login_register_status' => '1',
  'login_register_link' => 'Sign up here',
  'login_register_description' => 'Don\'t have an account?',
  'register_banner_status' => '1',
  'register_banner_title' => 'Register',
  'register_banner_description' => '',
  'register_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'register_status' => '1',
  'register_title' => 'Create Your Account',
  'register_description' => 'Join FreshMart for a seamless shopping experience',
  'register_personal_info' => 'Personal Information',
  'register_first_name' => 'First Name',
  'register_last_name' => 'Last Name',
  'register_account_info' => 'Account Information',
  'register_email' => 'Email Address',
  'register_email_note' => 'We\'ll send order confirmations and receipts to this email',
  'register_phone' => 'Phone Number',
  'register_phone_note' => 'For order updates and delivery notifications',
  'register_password' => 'Password',
  'register_confirm_password' => 'Confirm Password',
  'register_password_note' => 'Password must be at least 8 characters long and include a mix of letters, numbers, and special characters',
  'register_button' => 'Create Account',
  'register_terms' => 'I agree to the Terms & Conditions and Privacy Policy. I confirm that I am at least 18 years old.',
  'register_login_status' => '1',
  'register_login_link' => 'Sign In here',
  'register_login_description' => 'Already have an account?',
  'forgot_banner_status' => '1',
  'forgot_banner_title' => 'Forgot Password',
  'forgot_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'forgot_password_status' => '1',
  'forgot_password_title' => 'Forgot Your Password?',
  'forgot_password_description' => 'Enter your email to receive a password reset link.',
  'forgot_password_email' => 'Email Address',
  'forgot_password_button' => 'Reset Password',
  'forgot_password_back_button' => 'Back to login',
  'forgot_password_back_description' => 'Remember your password?',
  'reset_banner_status' => '1',
  'reset_banner_title' => 'Reset Password',
  'reset_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'reset_password_status' => '1',
  'reset_password_title' => 'Reset Your Password?',
  'reset_password_description' => 'Enter your email to receive a password reset link.',
  'reset_password_email' => 'Email Address',
  'reset_password_pwd' => 'Password',
  'reset_password_confirm_pwd' => 'Confirm Password',
  'reset_password_button' => 'Reset Password',
  'faq_banner_status' => '1',
  'faq_banner_title' => 'faqs',
  'faq_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'faq_list_status' => '1',
  'wishlist_banner_status' => '1',
  'wishlist_banner_title' => 'Wishlist',
  'wishlist_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'wishlist_status' => '1',
  'wishlist_button' => 'Continue Shopping',
  'wishlist_button_link' => '#',
  'error_banner_status' => '1',
  'error_banner_title' => 'Error',
  'error_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'error_status' => '1',
  'error_code' => '404',
  'error_title' => 'Oops! Page Not Found!',
  'error_description' => 'We couldn\'t find the page you\'re looking for. The page may have moved, or it might no longer be available.',
  'error_product_button' => 'Browse Products',
  'error_product_button_link' => '#',
  'error_home_button' => 'Go to Homepage',
  'error_home_button_link' => '#',
  'menu_bar_status' => '1',
  'menu_bar_menu' => '',
  'announce_bar_status' => '1',
  'announce_bar_email' => 'info@freshpicks.com',
  'announce_bar_contact_no' => '+1 (234) 567-890',
  'header_status' => '1',
  'header_logo' => 'themes/beauty/assets/images/logo.png',
  'header_favicon' => 'themes/beauty/assets/images/favicon.png',
  'header_search_status' => '1',
  'header_search_title' => 'Search',
  'header_wishlist_status' => '1',
  'header_cart_status' => '1',
  'header_login_status' => '1',
  'footer_status' => '1',
  'footer_description' => 'Delivering farm-fresh organic groceries straight to your doorstep since 2010.',
  'footer_repeater' => '[{"icon":"fab fa-facebook-f","link":"https://www.facebook.com/"},{"icon":"fab fa-x-twitter","link":"https://x.com/"},{"icon":"fab fa-instagram","link":"https://www.instagram.com/"},{"icon":"fab fa-pinterest","link":"https://in.pinterest.com/"}]',
  'footer_logo' => 'themes/beauty/assets/images/footer-logo.png',
  'footer_menu_status' => '1',
  'footer_menu_repeater' => '[{"title":"Quick Links","menu":""},{"title":"Customer Service","menu":""}]',
  'footer_contact_status' => '1',
  'footer_contact_phone' => '(555) 123-4567',
  'footer_contact_email' => 'hello@beauty.com',
  'footer_contact_address' => '123 Organic Way, Green City',
  'footer_copy_right_status' => '1',
  'footer_contact_title' => 'Contact Us',
  'footer_copy_right_description' => '© 2025, Greentic rights reserved.',
  'cart_banner_status' => '1',
  'cart_banner_title' => 'Cart Details',
  'cart_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'cart_status' => '1',
  'cart_product_button_text' => 'Continue Shopping',
  'cart_product_button_link' => '#',
  'cart_clear_button_text' => 'Clear Cart',
  'cart_summary' => 'Order Summary',
  'cart_subtotal' => 'Subtotal',
  'cart_shipping' => 'Shipping',
  'cart_tax' => 'Tax',
  'cart_total' => 'Total',
  'cart_coupon_code' => 'Coupon Code',
  'cart_apply' => 'Apply',
  'cart_checkout' => 'Proceed to Checkout',
  'cart_checkout_button_link' => '#',
  'slider_status' => '1',
  'slider_repeater' => '[{"image": "themes/beauty/assets/images/home-banner-01.png","small_text": "FRESH & ORGANIC","big_text": "Nature Grownne We Care <span class=\\"text-primary\\">Always</span>","content": "Hand-picked harvests sent right with care to your doorstep today.","button_text": "Shop Now","button_link": "#"},{"image": "themes/beauty/assets/images/home-banner-02.png","small_text": "FRESH & ORGANIC", "big_text": "Pure Taste From Local <span class=\\"text-primary\\">Farms</span>","content": "Fresh ingredients grown naturally for hash to your familys meals.","button_text": "Shop Now","button_link": "#"},{"image": "themes/beauty/assets/images/home-banner-03.png","small_text": "FRESH & ORGANIC","big_text": "Wholesome Food For Every <span class=\\"text-primary\\">Table</span>","content": "Organic flavors crafted to bring wellness with care to your plate.","button_text": "Shop Now","button_link": "#"}]',
  'category_status' => '1',
  'category_title' => 'Product Categories',
  'category_button_text' => 'View All Categories',
  'category_button_link' => '#',
  'featured_product_status' => '1',
  'featured_product_title' => 'Featured Product',
  'bestseller_product_status' => '1',
  'bestseller_product_title' => 'Bestseller Product',
  'bestseller_product_button_text' => 'View All products',
  'bestseller_product_button_link' => '#',
  'top_category_status' => '1',
  'top_category_title' => 'Bestseller Product',
  'top_category_card_btn' => 'Shop Now',
  'top_category_button_text' => 'View All products',
  'top_category_button_title' => '#',
  'logos_status' => '1',
  'logos_title' => 'Trusted By Leading Brands',
  'more_offer_status' => '1',
  'more_offer_image' => 'themes/beauty/assets/images/offer-bg.png',
  'more_offer_title' => 'Save Up To 30% OFF',
  'more_offer_sub_title' => 'Big Deals trending of Week & fresh products',
  'more_offer_button_text' => 'Shop Now',
  'more_offer_button_link' => '#',
  'article_status' => '1',
  'article_title' => 'Latest from Our Blog',
  'article_card_btn' => 'Read more',
  'article_button_text' => 'View All blog',
  'article_button_link' => '#',
  'testimonial_status' => '1',
  'testimonial_title' => 'What Our Customers Say',
  'newsletter_status' => '1',
  'newsletter_title' => 'Join Our Newsletter',
  'newsletter_sub_title' => 'Subscribe to get exclusive offers recipes, and health tips delivered to your inbox.',
  'newsletter_button' => 'Subscribe',
  'myaccount_image' => 'themes/beauty/assets/images/common-banner.png',
  'myaccount_title' => 'My Account',
  'myaccount_status' => '1',
  'account_dashboard_status' => '1',
  'account_dashboard_title' => 'Dashboard',
  'account_dashboard_greeting' => 'Hello',
  'account_dashboard_description' => 'From your account dashboard you can view your <span class="text-primary hover:underline">recent orders</span>, manage your <span class="text-primary hover:underline">shipping and billing addresses</span>, and <span class="text-primary hover:underline">edit your password and account details</span>',
  'account_dashboard_order' => '1',
  'account_dashboard_order_title' => 'Orders',
  'account_dashboard_order_desc' => 'View and track your orders',
  'account_dashboard_order_btn' => 'View Orders',
  'account_dashboard_address' => '1',
  'account_dashboard_address_title' => 'Addresses',
  'account_dashboard_address_desc' => 'Manage your addresses',
  'account_dashboard_address_btn' => 'Manage Addresses',
  'account_dashboard_wishlist' => '1',
  'account_dashboard_wishlist_title' => 'Wishlist',
  'account_dashboard_wishlist_desc' => 'View saved items',
  'account_dashboard_wishlist_btn' => 'View Wishlist',
  'account_dashboard_detail' => '1',
  'account_dashboard_detail_title' => 'Account Details',
  'account_dashboard_detail_desc' => 'View and track your details',
  'account_dashboard_detail_btn' => 'Edit Details',
  'account_recent_order_status' => '1',
  'account_recent_order_title' => 'Recent Orders',
  'account_recent_order_view_all' => 'View All Orders',
  'account_recent_order_action' => 'View',
  'account_detail_status' => '1',
  'account_detail_title' => 'Account Details',
  'account_detail_first_name' => 'First Name',
  'account_detail_last_name' => 'Last Name',
  'account_detail_email' => 'Email Address',
  'account_detail_phone' => 'Phone Number',
  'account_detail_pwd_change' => 'Password Change',
  'account_detail_pwd_note' => 'Leave blank to keep the same password',
  'account_detail_pwd_current' => 'Current Password',
  'account_detail_pwd_new' => 'New Password',
  'account_detail_pwd_confirm' => 'Confirm New Password',
  'account_detail_save' => 'Save Changes',
  'account_tab_status' => '1',
  'account_tab_customer_info' => '1',
  'account_tab_order_status' => '1',
  'account_tab_order_title' => 'Orders',
  'account_tab_address_status' => '1',
  'account_tab_address_title' => 'Addresses',
  'account_tab_wishlist_status' => '1',
  'account_tab_wishlist_title' => 'Wishlist',
  'account_tab_detail_status' => '1',
  'account_tab_detail_title' => 'Account Details',
  'account_tab_logout_status' => '1',
  'account_tab_logout_title' => 'Logout',
  'policy_banner_title' => 'Privacy Policy',
  'policy_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'privacy_policy_status' => '1',
  'product_list_title' => 'Shop',
  'product_list_best_seller_title' => 'You may also like',
  'product_list_best_seller_button_text' => 'VIEW All',
  'terms_policy_title' => 'Terms of Service',
  'terms_policy_sub_title' => 'OverView',
  'terms_policy_description' => 'This website is operated by Storepify | Minimal Multipurpose Shopify Theme. Throughout the site, the terms “we”, “us” and “our” refer to Storepify | Minimal Multipurpose Shopify Theme. Storepify | Minimal Multipurpose Shopify Theme offers this website, including all information, tools and Services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.',
  'wishlist_table' => 'Wishlist',
  'abouts_us_title' => 'This theme transcends the boundaries of gender, embracing fluidity and breaking down societal norms.',
  'abouts_us_description' => 'It encourages individuals to embrace their authentic selves, regardless of societal expectations. Androgynous designs intertwine masculine and feminine elements seamlessly, challenging the conventional notions of what is considered "appropriate" attire.',
  'abouts_us_image' => 'themes/beauty/assets/images/about-image.png',
  'abouts_us_full_title' => 'Our Mission',
  'abouts_us_full_description' => 'We believe everyone deserves access to high-quality, cutting-edge technology built with sustainable manufacturing practices. Our mission is to make premium electronics more accessible while supporting ethical manufacturers and reducing environmental impact.<br><br> By cutting out the middleman and working directly with manufacturers committed to quality and innovation, we can deliver devices that feature the latest technology, preserving maximum performance and value. <br><br> the innovation, we can deliver devices that feature the latest technology, preserving maximum performance and value Our mission is to make premium <br><br>We are driven by a commitment to transparency, fairness, and continuous improvement. Our goal is not only to offer exceptional products but also to promote responsible consumption and empower conscious choices in the tech industry.',
  'abouts_us_full_image' => 'themes/beauty/assets/images/about-image.png',
  'abouts_us_counter_repeater' => '[{"small_text":"45+","content":"Brand Partners."},{"small_text":"100+","content":"Quality Guarantee"},{"small_text":"10,000+","content":"Happy Customers"},{"small_text":"25,000+","content":"Monthly Shipments."}]',
  'abouts_us_full_title_second' => 'Driven by Innovation, Guided by Purpose',
  'abouts_us_full_description_second' => 'At the heart of everything we do is a passion for creating smarter, more sustainable technology solutions that elevate everyday life. We’re redefining what it means to own electronics by focusing on innovation, accessibility, and environmental responsibility.<br><br>Our direct-to-consumer approach eliminates unnecessary costs and barriers, allowing us to deliver premium devices without compromise. Each product reflects our dedication to thoughtful design, advanced performance, and long-term value. <br><br> the innovation, we can deliver devices that feature the latest technology, preserving maximum performance and value Our mission is to make premium manufacturing practices.<br><br>We collaborate with forward-thinking manufacturers who share our ethical and eco-conscious values, ensuring every step of our process—from sourcing to shipping—supports a cleaner, fairer future for all.',
  'abouts_us_full_image_second' => 'themes/beauty/assets/images/about-image2.png',
  'team_title' => 'Meet Our Team',
  'team_repeater' => '[{"image":"themes/beauty/assets/images/team-1.png","big_text":"Emily Johnson","content":"Former tech engineer with a passion for making cutting-edge technology accessible to everyone.","small_text":"Founder CEO"},{"image":"themes/beauty/assets/images/team-2.png","big_text":"Michael Chen","content":"Supply chain expert focused on creating efficient, eco-friendly distribution systems","small_text":"Head of Operations"}]',
  'cart_title' => 'Continue shopping',
  'cart_sub_total' => 'Subtotal',
  'cart_description' => 'Taxes and shipping calculated at checkout',
  'cart_shop_button' => 'Continue shopping',
  'cart_button_text' => 'GO TO CHECKOUT',
  'category_collection' => 'Collections',
  'billing_detail_title' => 'Billing Details',
  'shipping_title' => 'Shipping Details',
  'checkout_title' => 'Checkout',
  'checkout_button' => 'Place Order',
  'contact_us_banner_title' => 'Contact Us',
  'contact_us_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'contact_us_form_title' => 'Contact Us',
  'contact_us_map_location' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d193596.26002810575!2d-74.14431235114544!3d40.69728463488439!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sin!4v1746009273607!5m2!1sen!2sin',
  'contact_us_map_title' => 'Visit Our Store',
  'contact_us_map_description' => 'Our flagship store is conveniently located in the heart of Green Hills. Come visit us to see our full range of fresh, organic products.',
  'contact_social_list_status' => '1',
  'contact_social_list_repeater' => '[{"icon":"fab fa-facebook-f","link":"https://www.facebook.com/"},{"icon":"fab fa-x-twitter","link":"https://x.com/"},{"icon":"fab fa-instagram","link":"https://www.instagram.com/"},{"icon":"fab fa-youtube","link":"https://www.youtube.com/"},{"icon":"fab fa-pinterest","link":"https://in.pinterest.com/"}]',
  'blog_banner_title' => 'Blogs',
  'blog_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'article_banner_status' => '1',
  'article_banner_title' => 'Article',
  'article_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'abouts_us_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'abouts_us_banner_title' => 'About Us',
  'abouts_us_status' => '1',
  'terms_condition_banner_status' => '1',
  'terms_condition_banner_title' => 'Terms & Conditions',
  'terms_condition_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'terms_condition_policy_status' => '1',
  'terms_condition_policy_repeater' => '[{\\"title\\":\\"Step Into a World of Effortless Elegance\\",\\"summernote\\":\\"Simple cuts. Solid tones. Elevated basics. Our men’s lineup is designed for effortless dressing with a modern edge.\\"}]',
  'address_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'address_banner_title' => 'Address',
  'address_banner_status' => '1',
  'address_status' => '1',
  'address_title' => 'Your Addresses',
  'address_label' => 'Default',
  'address_add_button' => 'Add New Address',
  'address_edit_button' => 'Edit',
  'address_remove_button' => 'Remove',
  'address_default_text' => 'Set as Default',
  'abouts_us_full_status' => 1,
  'abouts_us_content_status' => 1,
  'abouts_us_image_status' => 1,
  'abouts_us_counter_status' => 1,
  'abouts_us_banner_status' => 1,
  'contact_us_form_status' => '1',
  'contact_us_banner_status' => '1',
  'collection_banner_status' => '1',
  'collection_banner_title' => 'Collection list',
  'collection_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'collection_all_status' => '1',
  'collection_all_title' => 'Browse All Collections',
  'collection_featured_status' => '1',
  'collection_featured_title' => 'Featured Collections',
  'collection_featured_button_text' => 'Shop Now',
  'policy_banner_status' => 1,
  'announce_bar_support_title' => '24/7 Support',
  'announce_bar_contact_us_title' => 'Contact Us :',
  'announce_bar_contact_us_value' => '0261-1234567',
  'logo_status' => 1,
  'login_button_status' => 1,
  'search_bar_status' => 1,
  'cart_button_status' => 1,
  'wishlist_button_status' => 1,
  'footer_logo_status' => 1,
  'footer_logo_description' => 'We bring you the latest trends in fashion at affordable prices. Quality clothing for everyone.',
  'social_list_status' => 1,
  'footer_newsletter_status' => 1,
  'footer_newsletter_title' => 'Join Our Newsletter',
  'footer_newsletter_sub_title' => 'Subscribe to our newsletter for the latest updates and offers.',
  'copy_right_status' => 1,
  'copy_right_description' => '© 2025, eCommerce Theme Powered by: workdo.io',
  'copy_right_footer_image_1' => 'themes/beauty/assets/images/ApplePay.png',
  'copy_right_footer_image_2' => 'themes/beauty/assets/images/Paypal.png',
  'more_offer_small_text' => 'More Offers',
  'more_offer_small_text_second' => 'Super Sale',
  'more_offer_big_text' => '30% Off Summer Collection',
  'more_offer_content' => 'Shop our curated summer essentials and refresh your wardrobe with our seasonal discounts',
  'logo_repeater' => '[  
    {
        "image": "themes/beauty/assets/images/partner-logo1.png"
    },
    {
        "image": "themes/beauty/assets/images/partner-logo2.png"
    },
    {
        "image": "themes/beauty/assets/images/partner-logo3.png"
    },
    {
        "image": "themes/beauty/assets/images/partner-logo4.png"
    },
    {
        "image": "themes/beauty/assets/images/partner-logo5.png"
    },
    {
        "image": "themes/beauty/assets/images/partner-logo2.png"
    },
    {
        "image": "themes/beauty/assets/images/partner-logo4.png"
    }
    ]',
  'collection_status' => 1,
  'product_status' => 1,
  'product_title' => 'Featured Products',
  'product_description' => 'Discover our curated selection of top-rated products that are sure to impress.',
  'category_description' => 'Explore our diverse range of categories to find exactly what you need.',
  'bestseller_status' => 1,
  'bestseller_title' => 'Best Sellers',
  'testimonial_sub_title' => 'Real feedback from our valued customers.',
  'blog_status' => 1,
  'blog_title' => 'Latest News',
  'blog_sub_title' => 'Stay updated with our latest news and trends.',
  'blog_button_text' => 'Read More',
  'service_status' => 1,
  'service_repeater' => '[
        {
          "image": "themes/beauty/assets/images/service.png",
          "title": "Exchange Offer",
          "content": "Easy To Exchange"
        },
        {
          "image": "themes/beauty/assets/images/service2.png",
          "title": "Big Savings",
          "content": "At Lowest Price"
        },
        {
          "image": "themes/beauty/assets/images/service3.png",
          "title": "24/7 Support",
          "content": "In Safe Hands"
        },
        {
          "image": "themes/beauty/assets/images/service4.png",
          "title": "Free Shipping",
          "content": "Delever To Door"
        }
      ]',
  'abouts_us_title_second' => 'Driven by Innovation, Guided by Purpose',
  'abouts_us_description_second' => 'At Greentic, we are not just a fashion brand; we are a movement driven by innovation and guided by purpose. Our commitment to quality, sustainability, and style sets us apart in the world of fashion. We believe that every piece of clothing tells a story, and we strive to create garments that resonate with our customers on a personal level. Join us on this journey as we redefine fashion for the modern world.',
  'abouts_us_image_second' => 'themes/beauty/assets/images/about-us2.png',
  'team_status' => 1,
  'team_slider' => 
  array (
    0 => 
    array (
      'image' => 'themes/beauty/assets/images/team1.png',
      'big_text' => 'John Doe',
      'small_text' => 'Founder & CEO',
      'content' => 'John is the visionary behind Greentic, leading the brand with passion and innovation.',
    ),
    1 => 
    array (
      'image' => 'themes/beauty/assets/images/team2.png',
      'big_text' => 'Jane Smith',
      'small_text' => 'Creative Director',
      'content' => 'Jane brings creativity and style to every collection, ensuring our designs are always on-trend.',
    ),
    2 => 
    array (
      'image' => 'themes/beauty/assets/images/team3.png',
      'big_text' => 'Mike Johnson',
      'small_text' => 'Marketing Manager',
      'content' => 'Mike drives our marketing strategies, connecting our brand with customers worldwide.',
    ),
  ),
  'contact_us_status' => 1,
  'contact_us_title' => 'Contact Us',
  'contact_us_location' => '123 Fashion Street, Style City, ST 12345',
  'contact_us_location_link' => 'https://www.google.com/maps',
  'contact_us_open_store' => 'Monday - Friday: 8am - 4pm',
  'contact_us_call_us' => '123-456-7890',
  'contact_us_email' => 'info@beauty.com',
  'contact_us_form_description' => 'We would love to hear from you! Please fill out the form below and we will get back to you as soon as possible.',
  'contact_us_form_button_text' => 'Send Message',
  'contact_us_map_status' => 1,
  'blog_description' => 'See The Latest News And Updates From Greentic',
  'blog_image' => 'themes/beauty/assets/images/common-banner.png',
  'article_description' => 'See The Latest News And Updates From Greentic',
  'article_image' => 'themes/beauty/assets/images/common-banner.png',
  'cart_image' => 'themes/beauty/assets/images/common-banner.png',
  'cart_button' => 'GO TO CHECKOUT',
  'checkout_status' => 1,
  'checkout_image' => 'themes/beauty/assets/images/common-banner.png',
  'checkout_description' => 'Checkout Your Selected Items',
  'checkout_order_title' => 'Order Summery',
  'checkout_order_button_title' => 'Complate Order',
  'error_button' => 'Return to Shop',
  'faq_content_status' => 1,
  'faq_content_title' => 'Frequently Asked Questions',
  'faq_content_description' => 'Find answers to common questions about our products, shipping, returns, and more.',
  'faq_content_image' => 'themes/beauty/assets/images/common-banner.png',
  'login_forgot_button' => 'Forgot Password?',
  'login_register_button' => 'Create an Account',
  'register_page_status' => 1,
  'register_page_image' => 'themes/beauty/assets/images/common-banner.png',
  'register_page_title' => 'Register',
  'register_page_description' => 'Please Register using account detail below.',
  'register_mobile' => 'Phone Number',
  'forgot_password_page_status' => 1,
  'forgot_password_page_title' => 'Forgot Password',
  'forgot_password_page_description' => 'Forgot Password',
  'forgot_password_page_image' => 'themes/beauty/assets/images/common-banner.png',
  'reset_password_page_status' => 1,
  'reset_password_page_title' => 'Reset Password',
  'reset_password_page_description' => 'Reset Password',
  'reset_password_page_image' => 'themes/beauty/assets/images/common-banner.png',
  'reset_password_password' => 'New Password',
  'reset_password_confirm_password' => 'Confirm Password',
  'myaccount_description' => 'Manage your account details, orders, and preferences.',
  'policy_status' => 1,
  'policy_title' => 'Privacy Policy',
  'policy_description' => 'Your privacy is important to us. Read our policy to understand how we handle your data.',
  'policy_image' => 'themes/beauty/assets/images/common-banner.png',
  'product_list_status' => 1,
  'product_list_best_seller_status' => 1,
  'product_page_status' => 1,
  'terms_policy_status' => 1,
  'terms_policy_image' => 'themes/beauty/assets/images/common-banner.png',
  'wishlist_title' => 'Wishlist',
  'wishlist_description' => 'View and manage your favorite products.',
  'wishlist_image' => 'themes/beauty/assets/images/common-banner.png',
  'menu_status' => 1,
  'login_back_status' => 1,
  'wishlist_best_seller_status' => 1,
  'wishlist_table_status' => 1,
  'product_list_banner_status' => 1,
  'product_list_banner_title' => 'Product List',
  'product_list_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'login_banner_status' => 1,
  'category_collection_status' => 1,
  'blog_top_products_status' => 1,
  'blog_recent_status' => 1,
  'blog_banner_status' => 1,
  'article_social_title' => 'Share this article:',
  'article_repeater' => "[{\"icon\":\"fab fa-facebook-f\",\"link\":\"https://www.facebook.com/\"},{\"icon\":\"fab fa-x-twitter\",\"link\":\"https://x.com/\"},{\"icon\":\"fab fa-instagram\",\"link\":\"https://www.instagram.com/\"},{\"icon\":\"fab fa-pinterest\",\"link\":\"https://in.pinterest.com/\"}]",
  'contact_info_status' => 1,
  'offer_section_status' => 1,
  'social_status' => 1,
  'checkout_banner_status' => 1,
  'checkout_banner_title' => 'Checkout Page',
  'checkout_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'billing_detail_status' => 1,
  'faq_form_status' => 1,
  'forgot_password_banner_status' => 1,
  'terms_content_status' => 1,
  'policy_privacy_status' => 1,
  'article_blog_title' => 'You Might Also Like',
  'article_blog_description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy.',
  'article_blog_button' => 'Go to products',
  'blog_button' => 'Read More',
  'background_image_title' => 'Title',
  'background_image_description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
  'background_image_button' => 'Go to Shop',
  'background_image' => 'themes/beauty/assets/images/banner-bg2.png',
  'best_product_title' => 'Our Loved category',
  'best_product_button' => 'Go to product',
  'best_product_sub_title' => 'Vegetables',
  'best_product_description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  'best_product_image' => 'themes/beauty/assets/images/banner-bg2.jpg',
  'best_seller_text' => 'Top Product',
  'best_seller_button' => 'Show more products',
  'product_type' => 'Latest Product',
  'product_category_list' => 'More Category',
  'category_slider_title' => 'Fall in love with amazing products',
  'category_slider_description' => 't of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
  'category_button' => 'View All',
  'footer_button' => 'themes/beauty/assets/images/youtube.svg',
  'footer_menu_title' => 'Information',
  'menu_bar' => 'Select Menu',
  'announce_bar' => 'Information',
  'announce_bar_button_text' => 'Shop now',
  'logo' => 'themes/beauty/assets/images/logo.png',
  'search_bar' => '1',
  'slider_left_image' => 'themes/beauty/assets/images/banner-bg1.png',
  'slider_center_image' => 'themes/beauty/assets/images/banner-bg2.png',
  'slider_right_image' => 'themes/beauty/assets/images/banner-bg3.png',
  'product_button_text' => 'View All',
  'top_category' => 'Top Category',
  'offer_status' => '1',
  'offer_title' => 'Limited Time Offer',
  'more_offer_button' => 'Shop the Sale',
  'logos_repeater' => '[{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"},{"image":"themes/beauty/assets/images/logo.png"}]',
  'register_fi_name' => 'First Name',
  'register_back' => 'Return to Shop',
  'service_image' => 'themes/beauty/assets/images/policy1.png',
  'service_title' => 'Free Shipping',
  'service_content' => 'On orders over $100',
  'wishlist_best_seller_title' => 'You may also like',
  'wishlist_best_seller_sub_title' => 'Bestsellers',
  'wishlist_best_seller_description' => 'If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the       middle of text.',
  'wishlist_best_seller_button_text' => 'VIEW All',
  'reset_password_confirm' => 'Confirm Password',
  'address_banner_image_title' => 'Address',
  
  'order_banner_status' => '1',
  'order_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'order_banner_title' => 'order',
  'order_list_status' => '1',
  'order_list_title' => 'Order History',
  'order_list_filter' => 'Filter',
  'order_list_button' => 'View Order Details',


  'track_banner_status' => '1',
  'track_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'track_banner_title' => 'Track Order',
  'track_form_status' => '1',
  'track_form_title' => 'Track Your Order',
  'track_form_description' => 'Enter your order number to track the status of your delivery. You can find your order number in the order confirmation email.',
  'track_form_number' => 'Order Number',
  'track_form_number_note' => 'Please enter your order number without spaces or dashes',
  'track_form_email' => 'Email Address',
  'track_form_button' => 'Track Order',
  'track_error_status' => '1',
  'track_error_title' => 'Order Not Found',
  'track_error_desc' => "We couldn't find an order matching the information you provided. Please check your order number and email address, and try again.",
  'track_error_button' => 'Try Again',
  'track_cancel_status' => '1',
  'track_cancel_title' => 'Your order is Cancel',
  'track_cancel_desc' => 'This order has been cancelled.',
  'track_cancel_button' => 'Continue shopping',

  'cms_page_banner_status' => '1',
  'cms_page_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'cms_page_status' => '1',

  'account_tab_support_ticket_status' => '1',
  'account_tab_support_ticket_title' => 'Support Ticket',
  'support_ticket_banner_status' => '1',
  'support_ticket_banner_title' => 'Support Ticket',
  'support_ticket_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'support_ticket_list_status' => '1',
  'support_ticket_list_title' => 'Support Ticket',
  'support_ticket_list_button' => 'Add Ticket',
  'order_cmp_banner_status' => '1',
  'order_cmp_banner_title' => 'Order Complete',
  'order_cmp_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'order_cmp_status' => '1',
  'order_cmp_message' => 'Order confirmed successfully!',
  'order_cmp_title' => 'Your order',
  'order_cmp_short_msg' => 'has been placed!',
  'order_cmp_description' => "Your order has been successfully processed! We've sent you an email confirmation. Our team will reach out if we need any additional information",
  'order_cmp_copy_btn' => 'Copy Link',
  'order_cmp_back_btn' => 'Back to shop',


  'order_info_banner_status' => '1',
  'order_info_banner_title' => 'order details',
  'order_info_banner_image' => 'themes/beauty/assets/images/common-banner.png',
  'order_info_status' => '1',
  'order_info_title' => 'your Order details',
  'order_info_item_status' => '1',
  'order_info_item_title' => 'Items from Order',
  'order_info_address_status' => '1',
  'order_info_address_ship' => 'Shipping Information',
  'order_info_address_bill' => 'Billing Information',
  'order_info_amount_status' => '1',
  'order_info_amount_title' => 'Extra Information',
  'order_info_note_status' => '1',
  'order_info_note_title' => 'Order updates for',
  'privacy_policy_repeater' => '[{"title":" Introduction","summernote":"<p>Welcome to Greentic. We respect your privacy and are committed to protecting it.</p>"},{"title":" Information Collection","summernote":"<p>We collect information you provide when you use our services, such as name and email.</p>"},{"title":" Use of Information","summernote":"<p>Your information helps us improve our services and communicate with you.</p>"},{"title":" Sharing Information","summernote":"<p>We do not share your personal data with third parties except as described in this policy.</p>"},{"title":" Data Security","summernote":"<p>We take reasonable steps to protect your data from unauthorized access and breaches.</p>"},{"title":" Your Rights","summernote":"<p>You have rights to access, correct, or delete your personal data.</p>"},{"title":" Cookies","summernote":"<p>We use cookies to enhance your experience on our website.</p>"},{"title":" Children’s Privacy","summernote":"<p>Our services are not intended for children under 13 years old.</p>"},{"title":" Changes to Policy","summernote":"<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the Last Updated date. You are advised to review this Privacy Policy periodically for any changes. </p>"},{"title":" Contact Us","summernote":"<p>If you have questions about this policy, contact us at privacy@Greentic.com.</p>"}]',
'privacy_policy_create_date' => '15 jun 2025',
'privacy_policy_note' => 'We value your privacy and are committed to protecting your personal information. Please read our privacy policy carefully.',

);
